name: Haskell CI (Stack)

on:
  push:
    branches: [ "feature/init" ]
  pull_request:
    branches: [ "feature/init" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: haskell-actions/setup@v2
      with:
        enable-stack: true
        stack-no-global: true

    - name: Cache Stack
      uses: actions/cache@v4
      env:
        cache-name: cache-stack
      with:
        # Cache global stack directory and local .stack-work
        path: |
          ~/.stack
          .stack-work
          shake/.stack-work
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('stack.yaml') }}-${{ hashFiles('shake/package.yaml') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-

    # Stack automatically picks up the stack.yaml in the root directory
    - name: Build and Test
      run: stack test